### ISSUE TITLE
Add Setting to disable hotkeys

### ISSUE THREAD

**Issue by rxqs** [Annosz/UIInfoSuite2#109]
I use the hotkey B in the game, and UI info suite has B override this to pull up the calendar. I wish this was toggleable, is there any way to fix this?

**Comment by bleem313** [comment]
The option used to be in the config to change or remove the hotkeys, but it seems the latest update (12/30) has removed this. Can't figure out if it was moved somewhere else or if it isn't possible to edit the hotkeys anymore.

**Comment by bleem313** [comment]
@rxqs I found where the setting got moved to. The config is now saved on a per farm basis. Inside the mod folder for UIInfoSuite2, you will find a data folder containing a config for each farm you have used with the mod. Open it and edit the lines "OpenCalendarKeybind" and "OpenQuestBoardKeybind" to change the key for that farm. Set them to "None" if you don't want hotkeys for them.

Optionally, you can make a default set of settings by copying one of the configs and naming it "JohnDoe_123456789" (name from the main config) with the settings you want to be applied by default to new farms. Alternatively, once you have the settings how you want in one farm, change the main config line "ApplyDefaultSettingsFromThisSave" to the name of the config for that save.

Though I would still love to have the hotkeys be editable from the in-game menu.

**Comment by Annosz** [comment]
Hi! I'm sorry if the latest update changed something that was not intended, I was making the  changes kind of blindly, because I wanted to fix the "the settings are not getting saved" issue which I did not even have on my computer... So maybe I reverted too much.

I will make sure that you can edit the OpenCalendarKeybind and OpenQuestBoardKeybind from the ingame menu too, and don't have to open the files for it.

Also, props for using the default settings, I think I will also have to make some notes somewhere on how one can use them (changing the main config file entry to you save game's name)

**Comment by bleem313** [comment]
I don't think it's an issue, it just wasn't where I expected it to be. I certainly don't mind the settings being per farm. I'm very grateful that you started maintaining this awesome mod.

**Comment by Annosz** [comment]
This is partly related to #47 and #104. Because it seems like it was mentioned so many time, I will work on this for the next update.
