### ISSUE TITLE
Issues with custom languages in the new version

### ISSUE THREAD

**Issue by Zangorr** [Annosz/UIInfoSuite2#159]
Hi! New version has introduced some issues, specifically with custom languages.

Queen of Sauce icon is not displaying at all with custom language.

Bundle names display only as numbers now:
![222](https://user-images.githubusercontent.com/91568890/162871211-8e6ee3f8-b07d-40ff-8bc2-e7b978972dec.png)

And also every time you load a save, all icons get duplicated (only with custom language):
![111](https://user-images.githubusercontent.com/91568890/162871256-7a937d11-01d0-4d58-a30d-f38d66974874.png)

**Comment by Annosz** [comment]
Hmm, I will add a pre-release tag to the file real quickly, so less people will download it.

The first issue was known for me, but it seemed like the root cause is not in this but in an other mod. If I delete UIInfoSuite2, load a save, exit to main menu, then load a save again (with custom language as you said), then in the community center the bundle names are not displayed, only these numbers are shown. Seems like another mod is breaking the name of the bundles, and now that we display it in UIInfoSuite2 it is more visible.
I did not have the time to check one-by-one which mod causes this bug. First I think I will add a temporary fix (eg. if it's a number, display the English name instead).

The other one I haven't seen, I will check out.
