### ISSUE TITLE
Superfluous Petting Icons

### ISSUE THREAD

**Issue by Zamiell** [Annosz/UIInfoSuite2#17]
One of the helpful features of the mod is that it will display a petting icon if you have not yet petted your animal on that particular day.

However, the mod does not account for the situation where you are at maximum friendship levels with the animal. In this situation, petting the animal is actually pointless, so the fact that the icon shows is superfluous and a bug.

Note that this bug applies to both the dog/cat and normal coop/barn animals.

**Comment by DiscipleOfEris** [comment]
I should point out that petting animals at maximum friendship isn't necessarily pointless. Failing to pet your coop/barn animals at maximum friendship reduces their friendship (and mood) by a small amount, meaning they won't be at max friendship the next day.

**Comment by Kimmerest** [comment]
I agree, to keep the barn and coop animals happy they need to be pet each day. Pets cannot decrease their friendship so as long as you are at maximum with your dog or cat, it’s reasonable to not pet them each day.  The isn’t true for the others though:

Actions that affect Mood are as follows (every 10 minutes refers to ingame minutes):

Petting (+32 to +36 dependent on animal type, double amount if player has chosen the Shepherd or Coopmaster Profession and the animal is of the relevant type)

**Comment by Zamiell** [comment]
Yes, you are correct. To clarify:

- Petting a dog/cat at max friendship is pointless.
- Petting a coop/barn animation at max friendship with an autopetter is pointless (assuming they are being fed).

However, I am mostly concerned with the former.

**Comment by Annosz** [comment]
For this issue and the [travelling cart icon](https://github.com/Annosz/UIInfoSuite2/issues/18) I was thinking about making new options to the mod's options page, like "Hide on max friendship" or "Hidewhen already visited", so the users can decide if they want to have these options (eg. they have an autopetter so petting its pointless on max friendship).

These options would be "embedded" under the normal options, because you can only finetune the behavior of the mod. I already made the possibility to[ add parent option](https://github.com/Annosz/UIInfoSuite2/commit/7d9ddcce4ff694e724b9b99f4accb76f002c4fce) for an other option for this embedding, now I'm just working on actually making the settings:

![image](https://user-images.githubusercontent.com/10620868/105389198-dc012d80-5c17-11eb-98c2-22c217d772f7.png)

**Comment by Zamiell** [comment]
Woot, thanks!
