### ISSUE TITLE
Release file?

### ISSUE THREAD

**Issue by AkiraTepes** [Annosz/UIInfoSuite2#178]
SMAPI says there's an update, but there's no release file.

**Comment by pedrocca2** [comment]
got the file?

**Comment by kyuMomo** [comment]
Yeah, I'm so confused.

**Comment by pedrocca2** [comment]
I think the creator forgot to put the update file to download

**Comment by jamesluke** [comment]
@Annosz forgot to upload the compiled version of 2.2.4. For the time being, use the previous release, available here: https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.3

See #181.

**Comment by Annosz** [comment]
Hello guys! It seems like Github is not letting me upload the release file somehow, it only shows “Something went really wrong, and we can’t process that file.” every time I try (first I did not saw the message that's why I released the mod without the file itself).

I deleted the new release, you can use 2.2.3 while I'm searching for a way to fix this.

**Comment by Annosz** [comment]
I will track the progress in #181 and close this issue as a duplicate.
