### ISSUE TITLE
Can't Launch/Load Mod

### ISSUE THREAD

**Issue by ExasperatedAnt** [Annosz/UIInfoSuite2#179]
When I open Stardew Valley through Smapi on Steam, it displays this error message:
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.

[SMAPI]       - UIInfoSuite2-master\UIInfoSuite2-master because it contains files, but none of them are manifest.json.

Any help fixing it would be very appreciated, thanks!

**Comment by pedrocca2** [comment]
got the file?

**Comment by jamesluke** [comment]
@Annosz forgot to upload the compiled version of 2.2.4. For the time being, use the previous release, available here: https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.3

See #181.

**Comment by Annosz** [comment]
Hello guys! It seems like Github is not letting me upload the release file somehow, it only shows “Something went really wrong, and we can’t process that file.” every time I try (first I did not saw the message that's why I released the mod without the file itself).

I deleted the new release, you can use 2.2.3 while I'm searching for a way to fix this.

**Comment by Annosz** [comment]
I will track the progress in #181 and close this issue as a duplicate.
