### ISSUE TITLE
Release file is not attatched to the new update. Only the source code zip and tar are present

### ISSUE THREAD

**Issue by ADemonicChild** [Annosz/UIInfoSuite2#181]

**Comment by Annosz** [comment]
Hello guys! It seems like Github is not letting me upload the release file somehow, it only shows “Something went really wrong, and we can’t process that file.” every time I try (first I did not saw the message that's why I released the mod without the file itself).

I deleted the new release, you can use 2.2.3 while I'm searching for a way to fix this.

**Comment by Annosz** [comment]
Seems like my antivirus was blocking the file upload. After disabling it, I was able to add the file.

Please check if it works correctly now.
