### ISSUE TITLE
The Ui Info Suit 2 can`t launch

### ISSUE THREAD

**Issue by 0verFreight** [Annosz/UIInfoSuite2#182]
I start Stardew normally, in the smapi screen appear this mensage: 

[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.

[SMAPI]       - UI Info Suite 2 2.2.3 because its DLL 'UIInfoSuite2.dll' doesn't exist.

What to do?

**Comment by jorstar** [comment]
As stated Here #https://github.com/Annosz/UIInfoSuite2/issues/178#issuecomment-1132398434 The correct file is not  available right this moment.

for now use https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.3 until the release files have been uploaded

**Comment by Annosz** [comment]
Hello guys! It seems like Github is not letting me upload the release file somehow, it only shows “Something went really wrong, and we can’t process that file.” every time I try (first I did not saw the message that's why I released the mod without the file itself).

I deleted the new release, you can use 2.2.3 while I'm searching for a way to fix this.

**Comment by Annosz** [comment]
I will track the progress in #181 and close this issue as a duplicate.

**Comment by 0verFreight** [comment]
Thanks you for your attention
