### ISSUE TITLE
Scaling UI makes clicking buttons impossible

### ISSUE THREAD

**Issue by jhammersholt** [Annosz/UIInfoSuite2#27]
If you scale the UI clicking on options menu, billboard is not where the graphics are (so you can't click them)
Scaling back to 100% makes them work as intented

Also the Pet animal icons are 'off'

Reproduce by scaling your UI

**Comment by jhammersholt** [comment]
It also affect the range overlay when placing Scarecrows (and possible also sprinklers, don't have them yet)

**Comment by DiscipleOfEris** [comment]
I fixed this in a PR for cdaragorn's version (before I knew this one was more active). https://github.com/cdaragorn/Ui-Info-Suite/pull/61

**Comment by Annosz** [comment]
Thanks for the work @DiscipleOfEris! I looked at your PR, and I like the soltuion very much (with the one centralized function). I would also like to have these changes in my version, but sadly I think automatic merging is pretty much impossible between the two projects now (I changed too much of the architecture).

Do you want to implement your changes here too or should I do it? I would gladly spend the time with copying your changes from the original PR to a new PR here, but then you would not be marked as the original creator of the code by Github. I don't know if thats okay with you :)

**Comment by DiscipleOfEris** [comment]
Give me a bit to investigate how much work it'd be to integrate with your fork. I'm working on improving gamepad support of the mod atm.

**Comment by n1spro** [comment]
> Give me a bit to investigate how much work it'd be to integrate with your fork. I'm working on improving gamepad support of the mod atm.

What are your successes in solving gamepad control problems? just tackling the same problem and wouldn't want to re-do the job.

**Comment by DiscipleOfEris** [comment]
@n1spro You can see my current work in https://github.com/cdaragorn/Ui-Info-Suite/pull/61. I haven't finished yet so I haven't started looking into making it compatible with Annosz' version. I think gamepad support is basically done outside of providing gamepad support for the menu when the "Use Controller Style Menus" option is enabled (I will probably make that a separate PR since it'll involve using Harmony).

Right now I'm working on fixing the NPC Map Locations not working reliably in split screen.
