### ISSUE TITLE
still missing information on modded crops with ver 2.2.9

### ISSUE THREAD

**Issue by kelvinyunan** [Annosz/UIInfoSuite2#278]
i've updated my UI info suite to the latest version (2.2.9) and everything regarding modded crops still doesn't show up (shop harvest prices, item hover information, crop and barrel times, etc.)

![missing shop harvest price](https://i.imgur.com/8n62pUb.png)

![latest version of uiinfomod](https://i.imgur.com/eNVFHrG.png)

**Comment by tqdv** [comment]
Hi ! I made my own version that works with DGA crops, you can download it from here: [UIInfoSuite2-v2.2.9-with-dga-integration.zip](https://github.com/tqdv/UIInfoSuite2/releases/download/2.2.10-0.tqdv.1.dga-integration/UIInfoSuite2-v2.2.9-with-dga-integration.zip). Tell me if that works.

I'm not sure if those changes will be added to the main mod because supporting DGA wasn't easy.
