### ISSUE TITLE
Upload to Nexus Mods

### ISSUE THREAD

**Issue by Pickysaurus** [Annosz/UIInfoSuite2#292]
Hi guys,

Picky from Nexus Mods here.

I was wondering if you'd consider sharing this mod on Nexus Mods. I was just helping a user with an SDV modding problem and got the confusing message "UI Info Suite 2.0.0 is outdated, use UI Info Suite 2". After getting to the bottom of that mystery we found this page. 

If you post it in our community it will make it significantly easier for players to find/download and you can earn rewards through our [Donation Points](https://www.nexusmods.com/about/donation-points) program for each unique download the mod gets. 

If you don't have the time to share it yourself, would you mind if I (or someone else) maintained a page? I note the mod has an MIT License, but it's always nice to ask first!

Thanks for sharing your mod :)

**Comment by Annosz** [comment]
Hi @Pickysaurus,

Thanks for dropping by :) Yes, I agree with you, it would be very nice to be on Nexus for the users, it's not good if a mod needs to be accessed from yet another different side. 

When I originally started updating the old UI Info Suite, it was indeed my intention to put it on Nexus (that was about 3 years ago), but after I was done with my initial changes, the original author @cdaragorn came around. He never really agreed to me publishing the mod separately, and we said I would integrate my changes. But in the end, none of my PRs got merged because he disappeared again, and now he has been MIA for 2years.

But because he was implying that he wants the changes merged and not released separately, I did not really dare to put it on Nexus (I have some mods already uploaded, so I'm familiar with the process, and I want to do it myself once it comes down to that). I don't know what would be a good move here, after all, it has now been exactly two years since I last heard from him (Jan 16, 2021 was the last activity on the main repo). Do you have any experienced suggestions from Nexus? :)

**Comment by Pickysaurus** [comment]
Thanks for replying.

The original repo doesn't list any license data: https://github.com/cdaragorn/Ui-Info-Suite

However, cdraragorn's mod page does have posted permissions: https://www.nexusmods.com/stardewvalley/mods/1150

![image](https://user-images.githubusercontent.com/31670524/213165012-65e1b415-2ba7-4f07-871f-690b03484733.png)

I suppose a question I have to understand this is how much of the mod is still primarily their work? 

If you've basically rewritten it along the same concept it may come under the "Asset Use" permission as you're only using small parts of the original mod. 

I can see that the original author logged into Nexus Mods in December 2022, so I can try and reach out to them and see if they can confirm permission. 

Even though UI Info Suite is incompatible with the latest version (on Android too IIRC?) they still earn Donation Points from it, so it's likely you'd need to agree on a fair split if they do grant permission.

**Comment by Annosz** [comment]
Hi,

I would say that this mod is still containing a lot of his work, it's not a full rewrite. It surely falls under the modification category, for which he marked he needs to give permission. So far I only got that for maintaining a working version on Github with the goal of integrating my updates back to the main mod.

Our last message exchange was in 2021, but I did not get an answer for that or my PRs on Github, but it's nice to know then he is still active on Nexus Mods. If you could reach out to him and ask him about the permission, that would be great for me, maybe we will be able to share the working version of the mod with the community.

**Comment by Pickysaurus** [comment]
Hi again,

I've sent them a PM on Nexus Mods, which you have been copied into. 

Hopefully we'll hear back!

**Comment by Stelios-Kourlis** [comment]
Hello,

Sorry for reviving this old issue but is there any update on the situation? It would be very helpful to have the mod on nexus. This is just my personal opinion but if cdaragorn hasn't responded in over 2 (now 3) years I think (again personal opinion) you should just upload it to nexus. Not only that but I think the majority of the community that uses UI Info Suite 2 hasn't even downloaded the original seeing as its been outdated for so long. I know if only ever used this version.

**Comment by Pickysaurus** [comment]
Hi guys,

I think we're at the point now where putting this version on Nexus Mods would be acceptable. 

If one of the maintainers wants to reach out to me on the Discord or Forums I'll see if we can arrange something :)

**Comment by Pickysaurus** [comment]
For transparency, what I think is best is if we add UI Info Suite 2 on a new mod page and I can mark the old one as "obsolete" with a redirect to the new one but I'm interested in chatting to @Annosz about how they feel this is best approached!

**Comment by Annosz** [comment]
Hi everyone! I left every decision on this topic in the hands of @drewhoener as the currently active maintainer of the project. I gave him permission to use anything from UIInfoSuite2 to create a new mod under his name (UIInfoSuite3? Who knows how will he decide?) and upload it to Nexus. As far as I know he is working with the separate release in mind since the v1.6 update, so I hope he can give a positive update on this topic :)

**Comment by Pickysaurus** [comment]
@drewhoener I wondered if you were able to chime in on this if you're still active?

**Comment by Pickysaurus** [comment]
I've now been able to talk with @drewhoener briefly. They intend to rewrite the mod and launch it under a different name. For the interim though, we should be able to post the current version under @Annosz's account. Just waiting for a few more replies and we'll be good to go on this :)
