### ISSUE TITLE
SMAPI won't let me use the mod

### ISSUE THREAD

**Issue by carmph342** [Annosz/UIInfoSuite2#311]
Whenever I try to start the game, it says that it can't load the mod because "the mod has files, but none of them are manifest.json. Any fix?
If it helps, I put the entire startup sequence into a notepad file:
[[SMAPI] SMAPI 3.18.3 with Stardew V.txt](https://github.com/Annosz/UIInfoSuite2/files/11298713/SMAPI.SMAPI.3.18.3.with.Stardew.V.txt)

**Comment by Annosz** [comment]
Hi! On the main page we have a section titlet [**If you are here to install the mod**](https://github.com/Annosz/UIInfoSuite2#if-you-are-here-to-install-the-mod), make sure you follow the instructions there. I think you downloaded it in a wrong way, because this _UIInfoSuite2-master_ filename it says is strange. Make sure the end result looks something like this:
![image](https://user-images.githubusercontent.com/10620868/233923701-cf1ba3a8-00cb-4545-808f-4441dbbec377.png)

**Comment by carmph342** [comment]
Thanks, didn't know downloading the zip was the same as downloading the source code.
