### ISSUE TITLE
Request: Ability to alter the Default Options of the UI suite

### ISSUE THREAD

**Issue by Zefferis** [Annosz/UIInfoSuite2#44]
As it stands currently, I've noticed that the UI Info Suite creates a new profile based on a characters username and that requires a player to manually edit settings to their liking after each new farm is created or joined (if they're playing with new names).

Would it be possible for the mod to have a configurable "Default" rather than automatically assuming that everyone wants every feature enabled?

**Comment by H1rag4mi** [comment]
I'm currently adding GenericModConfigMenu compatibility so we can edit default values.

**Comment by Annosz** [comment]
@H1rag4mi GenericModConfigMenu? Do you want to replace the existing config menu with it, or have it as a separate menu just for the default? Will that make possible to have separate options per character?

My first idea was that we can define a character name in the config.json, and when we create a new character we will pull the default settings from this defined character. I think this is not more than 15 minutes of coding and only changes the existing mod functionality very little. As we allready have a ready config menu, I think this would be a better approach.

**Comment by H1rag4mi** [comment]
I thought of adding GMCM as a default handler, but I am running into issues with reloading default values into the UIInfoSuite menu.

For now the change isn't all that big, H1rag4mi/UIInfoSuite2@868bdcd26e721b9799cabcf5ae24645a8f21b0a5

If you believe this is too much of a change let me know and I can change the way I'm doing it.

**Comment by Annosz** [comment]
Thanks, now I understand what GMCM does, and it looks really cool. I think we should add support for it even if we chose a different approach for the default values, because I hope that in the future there will be options in the config.json which we can edit.

As I see your method works perfectly, I think you are having issues with reloading default values because the mod has a separate per-character save built-in. It creates an XML each character to remember the settings, and thats why the settings you made in GMCM only overwrite the new characters (but this is exactly what we wanted :) ).

But I still think it would be better if we did not have a lot of separate options in the GMCM but only one line with a textbox where you can give the name of one of your characters, and it uses those settings as a default. Then we can use that character's settings in the ModEntry.cs in line 69-78, where we normally load the saved values from the XMLs. This has two advantages: we can keep our config.json clean and when we create a new option for our mod we do not have to register it in the GMCM, because it will already see it in the XMLs.

**Comment by Annosz** [comment]
Fixed by @Deflaktor. In the final solution, there is a new config file, which contains every setting, and works as a default for every character.

This is the same I guess to what @H1rag4mi suggested and did - I guess it will work with the mod config menu too. But I'm still concerned with the fact that it added an extra place in the code where a new functionality will need to be registered every time something is added. I will try to find a way to refactor this.
