### ISSUE TITLE
[Visual Bug]: Experience bar does not respect its option

### ISSUE THREAD

**Issue by drewhoener** [Annosz/UIInfoSuite2#446]
### Mod Version

Unknown

### Multiplayer

Single Player

### Visual Settings

Unknown

### Description

Reported by @EeveeTinn

> after the update the option "show experience gain" always shows up even after unchecking the option, same with the bar :)

Please provide your Mod Version and visual settings in a comment if possible

**Comment by EeveeTinn** [comment]
It seemed to have fixed itself - I restarted the game twice, and now the experience toggles work as they should, no idea what the problem was, but it happened right after I updated to v2.3.1 and then launched the game. I am on SMAPI 4.0.2.

![Screenshot_12](https://github.com/Annosz/UIInfoSuite2/assets/164864713/61638f7d-ca69-4693-9224-2f41b39980e2)
![Screenshot_13](https://github.com/Annosz/UIInfoSuite2/assets/164864713/94ad9b49-177d-4b80-a016-f81701ca17bd)

**Comment by drewhoener** [comment]
@EeveeTinn interesting...
If you can find any concrete way to reproduce, feel free to reopen this issue.
For now, I'm going to close it as unverified
