### ISSUE TITLE
[Bug]: SMAPI Error Repeating

### ISSUE THREAD

**Issue by littlerat07** [Annosz/UIInfoSuite2#573]
### Mod Version

v2.3.4

### Multiplayer

Single Player

### Issue

    The same error won't stop repeating. It's gotten so long I can't upload my SMAPI log because it says it's too large. The message will repeat about once a second. The message that keeps repeating is as follows:

[22:23:53 ERROR UI Info Suite 2] This mod failed in the Display.RenderedHud event. Technical details: 
NullReferenceException: Object reference not set to an instance of an object.
   at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderedHud(Object sender, RenderedHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowToolUpgradeStatus.cs:line 131
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
[22:23:53 ERROR UI Info Suite 2] This mod failed in the Display.RenderingHud event. Technical details: 
NullReferenceException: Object reference not set to an instance of an object.
![SMAPI](https://github.com/Annosz/UIInfoSuite2/assets/80924417/0d9daeab-0117-468b-b1d5-7343d4251071)

### Steps to Reproduce
Not sure.

**Comment by wulingxuan** [comment]
like #560

**Comment by faustooctavo** [comment]
Mod Version:
v2.3.4
Multiplayer:
Single Player
SMAPI Log:
https://smapi.io/log/79ac1fd117b44a0da0e97071601fdc09
Description
upon hovering over the icon indicated in the attached screenshot the menu screen closes out and the SMAPI Log begins to loop the previously mentioned error lines
Issue
<html><body>

20:27:47 | ERROR | UI Info Suite 2 | This mod failed in the Display.RenderedHud event. Technical details:  NullReferenceException: Object reference not set to an instance of an object.    at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderedHud(Object sender, RenderedHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowToolUpgradeStatus.cs:line 131    at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
-- | -- | -- | --
20:27:47 | ERROR | UI Info Suite 2 | This mod failed in the Display.RenderingHud event. Technical details:  NullReferenceException: Object reference not set to an instance of an object.    at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderingHud(Object sender, RenderingHudEventArgs e) in C:\Users\Drew\RiderProjects\DH-UIInfoSuite2\UIInfoSuite2\UIElements\ShowToolUpgradeStatus.cs:line 122    at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
 


</body>
</html>

![Screenshot 2024-06-29 202814](https://github.com/Annosz/UIInfoSuite2/assets/8053915/f86f2763-a12f-47de-abcc-10fe524df1fc)



My guess is the issue comes between an interaction of these mods:
UI Info Suite 2
Button's Extra Books
https://www.nexusmods.com/stardewvalley/mods/21526
More Books
https://www.nexusmods.com/stardewvalley/mods/23891
Special Power Utilities
https://www.nexusmods.com/stardewvalley/mods/22300

**Comment by faustooctavo** [comment]
found a new way to trigger this error, when you trigger the upgrade for the Pan, the "Show tool upgrade status" is activated the error starts looping, the issue seems to be related to UI attempting to render a HUD that doesn't exist, for the Pan, unchecking the "Show tool upgrade status" stops the error

**Comment by X3n0n3x** [comment]
> found a new way to trigger this error, when you trigger the upgrade for the Pan, the "Show tool upgrade status" is activated the error starts looping, the issue seems to be related to UI attempting to render a HUD that doesn't exist, for the Pan, unchecking the "Show tool upgrade status" stops the error

This seems to match my experience so far. I only noticed this issue for the first time just after I sent my Pan in for it's first upgrade, and upon retrieving the upgraded Pan from Clint the error spam in the SMAPI window stops. Notably, during the time the Pan was being upgraded, there was no UI icon showing how long until it finishes, unlike all the other tools.

**Comment by xyjddd** [comment]
Help! I had the same problem, and it made my game feel sluggish

**Comment by xyjddd** [comment]
I've tried many times, and this happens every time I ask Clint to upgrade the pan

**Comment by drewhoener** [comment]
Hi @xyjddd @X3n0n3x @faustooctavo @wulingxuan for now please try the hotfix in #560, it's been reported to work for others. I'll try and put out a real release tomorrow. Sorry for the delay, have had a lot to do with work lately

**Comment by X3n0n3x** [comment]
Thank you for the response!
I appreciate the hotfix, no rush on the full release.
