### ISSUE TITLE
[Visual Bug]: Npc menu show accurate hearts bug

### ISSUE THREAD

**Issue by wulingxuan** [Annosz/UIInfoSuite2#628]
### Mod Version

v2.3.6

### Multiplayer

Single Player

### Visual Settings

Ul Scale: 100%, Zoom: 100%

### Issue
![image](https://github.com/user-attachments/assets/d3133b16-1728-4927-a26f-37856d84fbf7)

Need to redraw the mouse after that.

https://github.com/Annosz/UIInfoSuite2/blob/d035b26abec8882c7601f8ebf916f071673ab8ab/UIInfoSuite2/UIElements/ShowAccurateHearts.cs#L132

**Comment by drewhoener** [comment]
@wulingxuan It's on the list of things to fix. A lot of subsystems in UIIS2 just draw the cursor again to mimic the effect of being on top so in my rewrite branch I have some harmony patches that inject the partial heart render right into the draw hearts method.
I wasn't planning on doing a temp fix of this, but if you'd like to contribute it I'll add it to a release.

Otherwise it'll be fixed when the rewrite is done
