### ISSUE TITLE
"Value cannot be null"

### ISSUE THREAD

**Issue by JokerBTA** [Annosz/UIInfoSuite2#70]
I was doing some testing tonight and saw this error pop in the log. I not sure what it was trying null.

Here is my log: https://smapi.io/log/259205d1551844e593293b24e9287067

**Comment by TaelFayre** [comment]
Someone on the discord had the same issue (Erin#1788) They added that they were trying to access something with a keybind [b] when the bug happened. 

Here's their log https://smapi.io/log/5e7ea9defe8f4b7fb9e793d59f59366f

**Comment by Deflaktor** [comment]
just submitted a PR to fix this issue

**Comment by JokerBTA** [comment]
I haven't had that error come up in quite sometime. I dunno what could have caused it.

**Comment by Deflaktor** [comment]
Its caused when you go into map directly without opening the menu

**Comment by Annosz** [comment]
Thanks for making this fix, sorry for taking so long to merge - I know that it's not a breaking issue, because the exception handling was on place (I suspect also thanks to @Deflaktor), so only the messages could be seen, but no effect on the gameplay, so I was not fast with the new release :)

I will merge the pending issues and create a new release.
