### ISSUE TITLE
Settings Reset

### ISSUE THREAD

**Issue by xChesirex** [Annosz/UIInfoSuite2#78]
The settings for all that UI can do are always reset whenever me and the host load into our MP farm save. We have NPC Map Locations and BetterRanching, so we don't need some of the settings for UI turned on ( And then some stuff I personally don't want to see that I turn off ) , if we don't turn those off, well, we get doubles on our maps. 
We're using the latest version of UI and the beta of the game. I'm unsure if a log would help, but here's one, I'm a farmhand on the farm, and yes, we both have it and have the same version. Host has the same issues as I do when it comes to her settings being reset upon loading in. 
https://smapi.io/log/b32957a20c30473c89bbe4f40b7db157

**Comment by Annosz** [comment]
Hello!
I've just think of a possible cause for your issue: the saved setting are stored in the Mods/UIInfoSuite2/data folder. Is it possible that you lost your settings when you updated the mod and deleted them?

**Comment by xChesirex** [comment]
When we initially updated, sure, but it happened the next time we relaunched the game when we hadn't touched anything in the folders

**Comment by rodrigovda** [comment]
I can confirm this happening to me. I disabled "ShowAnimalsNeedPets" using the ingame menu, it worked, but whenever I start the game, the setting is back to it's default. I've checked the config file and although the "last modified" date is consistent, the value of "ShowAnimalsNeedPets" is set to "true".

My guess is that something is failing to write into the file.

I have my "gaming" account in my PC as a non-admin account, maybe that could be the reason? In fact while writing this I went to check file permissions and surely the  "Users" group only has "read" and "access" permisison, however "athenticated users" have full control. Weird, since the mod is perfectly able to create the config file, it should be able to modify it too.

I've changed the folder permissions to grant "modify" to the "Users" group, and sure enough, the config file updated correctly and after re-launching the game the configs were not restarted.

So I'm pretty confident here this is a permissions issue that happens with non-admin users.

**Comment by xChesirex** [comment]
I use a laptop and have no other profiles on it, so my main account is the admin account. No other mod has this issue, so I don't believe it's a permissions thing.

**Comment by Annosz** [comment]
Hello guys! I tried to do some changing with the saving of the options, but as I never experienced the issue myself, I can't really say if it's working or not... Would you mind to do some testing? I share the new version here, and if you find that it works correctly, I will make a new release from it:
[UIInfoSuite2.zip](https://github.com/Annosz/UIInfoSuite2/files/7704839/UIInfoSuite2.zip)
